clear all; close all; clc;

% include = '-I"C:\Program Files (x86)\AMD APP\include"';
include = '-I"C:\Program Files (x86)\ATI Stream\include"';

% lib = '-lOpenCL -L"C:\Program Files (x86)\AMD APP\lib\x86_64"';
lib = '-lOpenCL -L"C:\Program Files (x86)\ATI Stream\lib\x86_64"';

compile = 'COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O3 /Ot"';
link = 'LINKFLAGS="$LINKFLAGS /MACHINE:X64"';

parameters = [ ...
    tokenize(include) ...
    tokenize(lib) ...
    tokenize(compile) ...
    tokenize(link)];

mexCreateLDPCDecoder = [ ...
    parameters ...
    cellstr('cpp\mexCreateLDPCDecoder.cpp') ...
    cellstr('cpp\clLDPCdec.cpp') ...
    cellstr('cpp\clException.cpp') ...
    cellstr('cpp\Util.cpp')];
mex(mexCreateLDPCDecoder{:});

mexDestroyLDPCDecoder = [ ...
    parameters ...
    cellstr('cpp\mexDestroyLDPCDecoder.cpp') ...
    cellstr('cpp\clLDPCdec.cpp') ...
    cellstr('cpp\clException.cpp')];
mex(mexDestroyLDPCDecoder{:});

mexDecodeLDPC = [ ...
    parameters ...
    cellstr('cpp\mexDecodeLDPC.cpp') ...
    cellstr('cpp\clLDPCdec.cpp') ...
    cellstr('cpp\clException.cpp')];
mex(mexDecodeLDPC{:});

% mex -I"C:\Program Files (x86)\AMD APP\include" ...
%     -lOpenCL -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
%     COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
%     LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
%     cpp\mexCreateLDPCDecoder.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp
    
% mex -I"C:\Program Files (x86)\AMD APP\include" ...
%     -lOpenCL -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
%     COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
%     LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
%     cpp\mexDestroyLDPCDecoder.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp

% mex -I"C:\Program Files (x86)\AMD APP\include" ...
%     -lOpenCL -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
%     COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
%     LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
%     cpp\mexDecodeLDPC.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp