clear all; close all; clc;

mex -I"C:\Program Files (x86)\AMD APP\include" ...
    -lOpenCL ...
    -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
    COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
    LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
    cpp\mexCreateLdpcDec.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp

mex -I"C:\Program Files (x86)\AMD APP\include" ...
    -lOpenCL ...
    -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
    COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
    LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
    cpp\mexDestroyLdpcDec.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp

mex -I"C:\Program Files (x86)\AMD APP\include" ...
    -lOpenCL ...
    -L"C:\Program Files (x86)\AMD APP\lib\x86_64" ...
    COMPFLAGS="$COMPFLAGS /MD /Qopenmp /O2" ...
    LINKFLAGS="$LINKFLAGS /MACHINE:X64" ...
    cpp\mexDecodeLdpc.cpp cpp\clLDPCdec.cpp cpp\clException.cpp cpp\Util.cpp

% mex('-I', ...
%     'C:\Program Files (x86)\ATI Stream\include', ...
%     '-lOpenCL', ...
%     '-L', ...
%     'C:\Program Files (x86)\ATI Stream\lib\x86_64', ...
%     'COMPFLAGS=/Qopenmp', ...
%     'mexCreateLdpcDec.cpp', 'clLDPCdec.cpp');
